version: '3.8'

services:
  crewai-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./knowledge:/app/knowledge
    restart: unless-stopped 